# Generated by Django 3.1.4 on 2022-02-06 22:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Apartment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('sale', models.BooleanField()),
                ('rent', models.BooleanField()),
                ('price', models.PositiveIntegerField()),
                ('description', models.TextField()),
                ('address', models.EmailField(max_length=254)),
                ('activated', models.BooleanField(default=False)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.CharField(max_length=200)),
                ('workers', models.PositiveIntegerField()),
                ('workers_number', models.PositiveIntegerField(blank=True)),
                ('email', models.TextField()),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apartments.apartment')),
            ],
        ),
    ]
